version: 2.1

commands:
 build-docker:
  description: "Build and deploy a docker box"
  parameters:
   box:
    type: string
    default: "minimal"
  steps:
   - checkout
   - run: ./docker/login.sh
   - run:
      no_output_timeout: 45m
      command: ./docker/build.sh << parameters.box >> $CIRCLE_BRANCH
   - run:
      no_output_timeout: 30m
      command: ./docker/push.sh << parameters.box >> $CIRCLE_BRANCH

jobs:
  build-binary-packages:
    docker:
     - image: nixos/nix
    resource_class: xlarge
    environment:
     NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - checkout
      - run:
         command: nix build --verbose -f default.nix pkgs.holochain

  merge-test-nix:
    docker:
     - image: nixos/nix
    resource_class: xlarge
    environment:
    steps:
      - checkout
      - run:
         command: nix-shell --argstr flavor "coreDev" --pure --run "cargo test --all-features"
      - run:
         command: nix-shell --argstr flavor "coreDev" --pure --run "cargo fmt --all -- --check"
      - run:
         command: nix-shell --argstr flavor "coreDev" --pure --run "cargo clippy -- \
                     -A clippy::nursery -D clippy::style -A clippy::cargo \
                     -A clippy::pedantic -A clippy::restriction \
                     -D clippy::complexity -D clippy::perf -D clippy::correctness"

  merge-test-native:
    docker:
      - image: cimg/rust:1.48.0
    steps:
      - checkout
      - run: |
         sudo apt-get update
         sudo apt-get install -y librust-openssl-dev
         cargo test --all-features
         cargo fmt --all -- --check
         cargo clippy -- \
            -A clippy::nursery -D clippy::style -A clippy::cargo \
            -A clippy::pedantic -A clippy::restriction \
            -D clippy::complexity -D clippy::perf -D clippy::correctness

  merge-test:
    docker:
     - image: holochain/holochain:circle.build.develop
       auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
    resource_class: xlarge
    environment:
     NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - checkout
      - run:
          command: nix-shell --argstr flavor ciLegacy --run hc-merge-test

  merge-test-mac:
   macos:
    xcode: "12.0.0"
   resource_class: xlarge
   environment:
    NIXPKGS_ALLOW_UNFREE: 1
   steps:
    - checkout
    - run:
       name: Test on mac
       no_output_timeout: 30m
       command: |
        # fix for "too many open files" that breaks tokio and lmdb
        ulimit -n 10240
        # catalina nixos install
        sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
        . /Users/distiller/.nix-profile/etc/profile.d/nix.sh
        # do tests
        nix-shell --argstr flavor ciLegacy --run hc-merge-test

  docker-build-latest:
   resource_class: large
   machine: true
   steps:
    - build-docker:
       box: latest

  docker-build-circle-build:
   resource_class: large
   machine: true
   steps:
    - build-docker:
       box: circle.build

workflows:
 version: 2.1
 tests:
  jobs:
   # - build-binary-packages
   # - merge-test
   # - merge-test-nix
   - merge-test-native
   # - merge-test-mac
 docker-builds:
  triggers:
   - schedule:
      cron: "0 0 * * *"
      filters:
       branches:
        only:
         - develop
         - master
  jobs:
   - docker-build-latest
   - docker-build-circle-build:
      requires:
       - docker-build-latest
